# Change the default theme to be use when building the site with Hugo
[module]
    
  [[module.mounts]]
    source = "content"
    target = "content/docs"

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "layouts"
    target = "layouts"

  [[module.mounts]]
    source = "data"
    target = "data"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "i18n"
    target = "i18n"

  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"

ignoreFiles = [ "\\.ttf$", "\\.woff$", "\\.woff2$", "\\.eot$" ]

[permalinks]
  "/" = "/docs/:section/:title/"
  "faqs" = "/docs/:section/:title/"
  "glossaries" = "/docs/:section/:title/"
  "how_tos" = "/docs/:section/:title/"
  "integrations" = "/docs/:section/:title/"
  "m3coordinators" = "/docs/:section/:title/"
  "m3dbs" = "/docs/:section/:title/"
  "m3querys" = "/docs/:section/:title/"
  "operational_guides" = "/docs/:section/:title/"
  "overviews" = "/docs/:section/:title/"
  "quickstarts" = "/docs/:section/:title/"
  "troubleshootings" = "/docs/:section/:title/"

languageCode = "en-US"
defaultContentLanguage = "en"

title = "M3DB Documentation"
metaDataFormat = "yaml"

# Highlighting config.
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsUseClassic = false

enableGitInfo = false

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
# id = "UA-00000000-0"

#fullversion = "v1.18.0"
#version = "v1.18"
# githubbranch = "master"
# docsbranch = "master"
# deprecated = false
#currentUrl = "https://kubernetes.io/home/"
#nextUrl = "https://kubernetes-io-vnext-staging.netlify.com/"
# githubWebsiteRepo = "https://github.com/m3db/m3"
# githubWebsiteRaw = "raw.githubusercontent.com/m3db/m3"

# Enable Lunr.js offline search
offlineSearch = true

[params]
  # Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page. 
  # Useful to give opportunity to people to create merge request for your doc.
  # See the config.toml file from this documentation site to have an example.
  # Author of the site, will be used in meta information
  author = "m3"
  # Description of the site, will be used in meta information
  description = "m3documentation"
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = false
  # Disable search function. It will hide search bar
  disableSearch = false
  # Javascript and CSS cache are automatically busted when new version of site is generated. 
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = true
  # A title for shortcuts in menu is set by default. Set this to true to disable it. 
  disableShortcutsTitle = false
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = false
  # Hide breadcrumbs in the header and only show the current page title
  disableBreadcrumb = true
  # Hide Next and Previous page buttons normally displayed full height beside content
  disableNextPrev = true
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"
  twitter = "m3db_io"
  disableHomeIcon = true
  gettingStartedLink = "/docs/quickstart/docker"

  [params.api]
    localCordinator = "http://localhost:7201/"
    apiEndpoint = "api/v1/"

# [[params.versions]]
#   version = "1.0"
#   url = "https://master.kubeflow.org"
#   [[params.versions]]
#   version = "0.9"
#   url = "https://master.kubeflow.org"
# version_menu = "Versions"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.tableOfContents]
      endLevel = 3
      ordered = false
      startLevel = 2
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true

[[menu.socials]]
name = "/images/slack_logo-light.svg"
identifier = "ms"
url = "https://bit.ly/m3slack"
weight = 10

[[menu.socials]]
name = "/images/github_logo-light.svg"
url = "https://github.com/m3db/m3"
weight = 11

[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i> <label>Github repo</label>"
identifier = "ds"
url = "https://github.com/m3db/m3"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-slack'></i> <label>Slack</label>"
url = "https://bit.ly/m3slack"
weight = 11

[[menu.shortcuts]]
name = "<i class='fa fa-inbox'></i> <label>Mailing list</label>"
url = "https://groups.google.com/forum/#!forum/m3db"
weight = 12

[outputs]
home = [ "HTML", "RSS", "JSON"]
page = [ "HTML"]
section = [ "HTML"]
chapter = [ "HTML"]
